# Generated by Django 4.0.4 on 2022-04-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
