# Generated by Django 4.0.4 on 2022-04-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_waphone_alter_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=64)),
            ],
        ),
    ]
