# Generated by Django 4.0.4 on 2022-04-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_signuprequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signuprequest',
            old_name='mail',
            new_name='email',
        ),
    ]
