# Generated by Django 4.0.4 on 2022-04-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_rename_mail_signuprequest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuprequest',
            name='code',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
