# Generated by Django 4.0.4 on 2022-04-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_animale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animale_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], default='dog', max_length=50),
        ),
    ]
