# Generated by Django 4.0.4 on 2022-04-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_animale_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='animale_type',
            new_name='animal_type',
        ),
    ]
