# Generated by Django 4.0.4 on 2022-04-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pet_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='type',
            new_name='advert_type',
        ),
    ]
