# Generated by Django 4.0.4 on 2022-04-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_alter_pet_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.TextField()),
                ('fa_icon', models.CharField(max_length=20)),
            ],
        ),
    ]
