# Generated by Django 4.0.4 on 2022-04-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='fa_icon',
            field=models.CharField(max_length=50),
        ),
    ]
