# Generated by Django 4.0.4 on 2022-04-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_for_pet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='for_pet_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], default='dog', max_length=20),
        ),
    ]
